# TRANSLOADIT = Transloadit.new(
  # :key    => ENV["TRANSLOADIT_AUTH_KEY"],
  # :secret => ENV["TRANSLOADIT_AUTH_SECRET"]
# )

AWS_BUCKET = ENV["AWS_BUCKET"]
AWS_KEY = ENV["AWS_ACCESS_KEY"]
AWS_SECRET = ENV["AWS_SECRET_ACCESS_KEY"]
